### ISSUE TITLE
FileNotFoundError..

### ISSUE THREAD

**Issue by RoyAn2386** [Meize0729/RSBuilding#3]
Hi Everyone, 

I already set all environment up, but when i run Test mode for ViT_B checkpoint, an error occur like the below image.

![a](https://github.com/Meize0729/RSBuilding/assets/93242926/47474c68-3ac3-4d9c-a5d7-1538cc7cca08)

Can everyone help me, Please~~

**Comment by kuyhni** [comment]
I got the above error while trying to test the model with the pre-trained model ViT_B downloaded from baidu. I followed the instructions on GitHub to install and set up the environment, but I got the above error.

**Comment by kuyhni** [comment]
I have a question
1. I downloaded the material on github. And I'm trying to use the pre-trained Swin_T or ViT_B models downloaded from baidu.
2. so, what should I modify in the downloaded one?
3. additionally, we are going to train it with our own data. What should we do?

**Comment by kuaiqushangzixiba** [comment]
/data/RSBuilding-main/configs_finetune/_base_/datasets/standard_512x512_foundationdataset.py

I ran into the same problem, you need to change the sixth line, but I don't know how the author handled test4.txt, so the code still can't run

**Comment by kuyhni** [comment]
Thank you for answer!

-----------------------원본 메세지-----------------------
보낸사람: ***@***.***>
받는사람: "Meize0729/RSBuilding" ***@***.***>
참조: "kuyhni" ***@***.***>, "Comment" ***@***.***>
보낸날짜: 2024-04-16 16:17:14 GMT +0900 (Asia/Seoul)제목: Re: [Meize0729/RSBuilding] FileNotFoundError.. (Issue #3)
 
 

/data/RSBuilding-main/configs_finetune/base/datasets/standard_512x512_foundationdataset.py
I ran into the same problem, you need to change the sixth line, but I don't know how the author handled test4.txt, so the code still can't run
